steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t',
      'asia-south1-docker.pkg.dev/ci-cd-pipeline-464008/go-app-repo/go-ci-cd-app:latest', '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'asia-south1-docker.pkg.dev/ci-cd-pipeline-464008/go-app-repo/go-ci-cd-app:latest'
    ]

images:
  - 'asia-south1-docker.pkg.dev/ci-cd-pipeline-464008/go-app-repo/go-ci-cd-app:latest'

logsBucket: gs://ci-cd-logs-bucket