name: Go CI/CD Pipeline 

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build-test-push:
        name: Build, Test, Push Docker Image
        runs-on: ubuntu-latest

        steps: 
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: 1.21
            
            - name: Run Unit Tests
              run: go test ./...

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              
            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-ci-cd-app:latest